//
//  EmojiSet.swift
//  Emoji Recognizer
//
//  Created by Алексей Агеев on 04.12.2020.
//

import Combine

class EmojiSet: ObservableObject {
    
    static var shared = EmojiSet()
    
    @Published var emojiArray = [
    Emoji(
        image: "😀",
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        jaw: .jawOpen),
    Emoji(
        image: "😃",
        leftEye: .eyeWideLeft,
        rightEye: .eyeWideRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        jaw: .jawOpen),
    Emoji(
        image: "😄",
        leftEye: .eyeSquintLeft,
        rightEye: .eyeSquintRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        jaw: .jawOpen),
    Emoji(
        image: "😁",
        leftEye: .eyeSquintLeft,
        rightEye: .eyeSquintRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight),
    Emoji(
        image: "😆",
        leftEye: .eyeBlinkLeft,
        rightEye: .eyeBlinkRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        jaw: .jawOpen),
    Emoji(
        image: "😅",
        leftEye: .eyeSquintLeft,
        rightEye: .eyeSquintRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        jaw: .jawOpen),
    Emoji(
        image: "😂",
        leftBrow: .browDownLeft,
        rightBrow: .browDownRight,
        leftEye: .eyeBlinkLeft,
        rightEye: .eyeBlinkRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: .jawOpen),
    Emoji(
        image: "🤣",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeBlinkLeft,
        rightEye: .eyeBlinkRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: .jawOpen),
    Emoji(
        image: "🥲",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: nil,
        rightEye: nil,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "☺️",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeBlinkLeft,
        rightEye: .eyeBlinkRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😊",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeSquintLeft,
        rightEye: .eyeSquintRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😇",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeSquintLeft,
        rightEye: .eyeSquintRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "🙂",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: nil,
        rightEye: nil,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "🙃",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: nil,
        rightEye: nil,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😉",
        leftBrow: nil,
        rightBrow: .browDownRight,
        leftEye: nil,
        rightEye: .eyeBlinkRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😉",
        leftBrow: .browDownLeft,
        rightBrow: nil,
        leftEye: .eyeBlinkLeft,
        rightEye: nil,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😌",
        leftBrow: .browDownLeft,
        rightBrow: .browDownRight,
        leftEye: .eyeBlinkLeft,
        rightEye: .eyeBlinkRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😍",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeWideLeft,
        rightEye: .eyeWideRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: .jawOpen),
    Emoji(
        image: "🥰",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeBlinkLeft,
        rightEye: .eyeBlinkRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😘",
        leftBrow: nil,
        rightBrow: .browDownRight,
        leftEye: nil,
        rightEye: .eyeBlinkRight,
        leftMouth: .mouthPucker,
        rightMouth: .mouthPucker,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😗",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: nil,
        rightEye: nil,
        leftMouth: .mouthPucker,
        rightMouth: .mouthPucker,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😙",
        leftBrow: .eyeSquintLeft,
        rightBrow: .eyeSquintRight,
        leftEye: nil,
        rightEye: nil,
        leftMouth: .mouthPucker,
        rightMouth: .mouthPucker,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😚",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeBlinkLeft,
        rightEye: .eyeBlinkRight,
        leftMouth: .mouthPucker,
        rightMouth: .mouthPucker,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😋",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeBlinkLeft,
        rightEye: .eyeBlinkRight,
        leftMouth: nil,
        rightMouth: nil,
        tongue: .tongueOut,
        jaw: nil),
    Emoji(
        image: "😛",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: nil,
        rightEye: nil,
        leftMouth: nil,
        rightMouth: nil,
        tongue: .tongueOut,
        jaw: .jawOpen),
    Emoji(
        image: "😝",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeBlinkLeft,
        rightEye: .eyeBlinkLeft,
        leftMouth: nil,
        rightMouth: nil,
        tongue: .tongueOut,
        jaw: .jawOpen),
    Emoji(
        image: "😜",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeBlinkLeft,
        rightEye: nil,
        leftMouth: nil,
        rightMouth: nil,
        tongue: .tongueOut,
        jaw: .jawOpen),
    Emoji(
        image: "😜",
        leftBrow: nil,
        rightBrow: .eyeBlinkRight,
        leftEye: nil,
        rightEye: nil,
        leftMouth: nil,
        rightMouth: nil,
        tongue: .tongueOut,
        jaw: .jawOpen),
    Emoji(
        image: "🤪",
        leftBrow: nil,
        rightBrow: .eyeBlinkRight,
        leftEye: nil,
        rightEye: nil,
        leftMouth: nil,
        rightMouth: nil,
        tongue: .tongueOut,
        jaw: .jawOpen),
    Emoji(
        image: "🤨",
        leftBrow: .browOuterUpLeft,
        rightBrow: .browDownRight,
        leftEye: nil,
        rightEye: nil,
        leftMouth: .mouthDimpleLeft,
        rightMouth: .mouthDimpleRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "🤨",
        leftBrow: .browDownLeft,
        rightBrow: .browOuterUpRight,
        leftEye: nil,
        rightEye: nil,
        leftMouth: .mouthDimpleLeft,
        rightMouth: .mouthDimpleLeft,
        tongue: nil,
        jaw: nil),
//    Emoji(
//        image: "🧐",
//        leftBrow: nil,
//        rightBrow: nil,
//        leftEye: nil,
//        rightEye: nil,
//        leftMouth: .mouthSmileLeft,
//        rightMouth: .mouthSmileRight,
//        tongue: nil,
//        jaw: .jawOpen),
//    Emoji(
//        image: "🤓",
//        leftBrow: nil,
//        rightBrow: nil,
//        leftEye: nil,
//        rightEye: nil,
//        leftMouth: .mouthSmileLeft,
//        rightMouth: .mouthSmileRight,
//        tongue: nil,
//        jaw: .jawOpen),
//    Emoji(
//        image: "😎",
//        leftBrow: nil,
//        rightBrow: nil,
//        leftEye: nil,
//        rightEye: nil,
//        leftMouth: .mouthSmileLeft,
//        rightMouth: .mouthSmileRight,
//        tongue: nil,
//        jaw: .jawOpen),
//    Emoji(
//        image: "🥸",
//        leftBrow: nil,
//        rightBrow: nil,
//        leftEye: nil,
//        rightEye: nil,
//        leftMouth: .mouthSmileLeft,
//        rightMouth: .mouthSmileRight,
//        tongue: nil,
//        jaw: .jawOpen),
//    Emoji(
//        image: "🤩",
//        leftBrow: nil,
//        rightBrow: nil,
//        leftEye: nil,
//        rightEye: nil,
//        leftMouth: .mouthSmileLeft,
//        rightMouth: .mouthSmileRight,
//        tongue: nil,
//        jaw: .jawOpen),
//    Emoji(
//        image: "🥳",
//        leftBrow: nil,
//        rightBrow: nil,
//        leftEye: nil,
//        rightEye: nil,
//        leftMouth: .mouthSmileLeft,
//        rightMouth: .mouthSmileRight,
//        tongue: nil,
//        jaw: .jawOpen),
//    Emoji(
//        image: "😏",
//        leftBrow: nil,
//        rightBrow: nil,
//        leftEye: nil,
//        rightEye: nil,
//        leftMouth: .mouthSmileLeft,
//        rightMouth: .mouthSmileRight,
//        tongue: nil,
//        jaw: .jawOpen),
//    Emoji(
//        image: "😒",
//        leftBrow: nil,
//        rightBrow: nil,
//        leftEye: nil,
//        rightEye: nil,
//        leftMouth: .mouthSmileLeft,
//        rightMouth: .mouthSmileRight,
//        tongue: nil,
//        jaw: .jawOpen),
//    Emoji(
//        image: "😞",
//        leftBrow: nil,
//        rightBrow: nil,
//        leftEye: nil,
//        rightEye: nil,
//        leftMouth: .mouthSmileLeft,
//        rightMouth: .mouthSmileRight,
//        tongue: nil,
//        jaw: .jawOpen),
//    Emoji(
//        image: "😔",
//        leftBrow: nil,
//        rightBrow: nil,
//        leftEye: nil,
//        rightEye: nil,
//        leftMouth: .mouthSmileLeft,
//        rightMouth: .mouthSmileRight,
//        tongue: nil,
//        jaw: .jawOpen),
//    Emoji(
//        image: "😟",
//        leftBrow: nil,
//        rightBrow: nil,
//        leftEye: nil,
//        rightEye: nil,
//        leftMouth: .mouthSmileLeft,
//        rightMouth: .mouthSmileRight,
//        tongue: nil,
//        jaw: .jawOpen),
//    Emoji(
//        image: "😕",
//        leftBrow: nil,
//        rightBrow: nil,
//        leftEye: nil,
//        rightEye: nil,
//        leftMouth: .mouthSmileLeft,
//        rightMouth: .mouthSmileRight,
//        tongue: nil,
//        jaw: .jawOpen),
//    Emoji(
//        image: "🙁",
//        leftBrow: nil,
//        rightBrow: nil,
//        leftEye: nil,
//        rightEye: nil,
//        leftMouth: .mouthSmileLeft,
//        rightMouth: .mouthSmileRight,
//        tongue: nil,
//        jaw: .jawOpen),
//    Emoji(
//        image: "☹️",
//        leftBrow: nil,
//        rightBrow: nil,
//        leftEye: nil,
//        rightEye: nil,
//        leftMouth: .mouthSmileLeft,
//        rightMouth: .mouthSmileRight,
//        tongue: nil,
//        jaw: .jawOpen),
//    Emoji(
//        image: "😣",
//        leftBrow: nil,
//        rightBrow: nil,
//        leftEye: nil,
//        rightEye: nil,
//        leftMouth: .mouthSmileLeft,
//        rightMouth: .mouthSmileRight,
//        tongue: nil,
//        jaw: .jawOpen),
    Emoji(
        image: "😐",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: nil,
        rightEye: nil,
        leftMouth: .mouthClose,
        rightMouth: .mouthClose,
        tongue: nil,
        jaw: nil),
//    Emoji(
//        image: "😖",
//        leftBrow: nil,
//        rightBrow: nil,
//        leftEye: nil,
//        rightEye: nil,
//        leftMouth: .mouthSmileLeft,
//        rightMouth: .mouthSmileRight,
//        tongue: nil,
//        jaw: .jawOpen),
]
}
//                😫 😩 🥺 😢 😭 😤 😠 😡 🤬 🤯 😳 🥵 🥶 😱 😨 😰 😥 😓 🤔 🤭 🤫 😶 😐 😑 😬 🙄 😯 😦 😧 😮 😲 🥱 🤤 😪 😵 🤐 🥴 🤢 🤮 🤒 🤕 🤑 🤠 😈 👿 👹 👺 🤡 💩 👻 👽 🤖 😺 😸 😹 😻 😼 😽 🙀 😿 😾 👀 👅 🙍 🙎 🦹 🐵 🙈 🙊 🌝 🌚 🗿

