//
//  EmojiSet.swift
//  Emoji Recognizer
//
//  Created by Алексей Агеев on 04.12.2020.
//

import Combine

class EmojiSet: ObservableObject {
    
    static var shared = EmojiSet()
    
    @Published var emojiArray = [
    Emoji(
        image: "😀",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: nil,
        rightEye: nil,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: .jawOpen),
    Emoji(
        image: "😃",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeWideLeft,
        rightEye: .eyeWideRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: .jawOpen),
    Emoji(
        image: "😄",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeSquintLeft,
        rightEye: .eyeSquintRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: .jawOpen),
    Emoji(
        image: "😁",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeSquintLeft,
        rightEye: .eyeSquintRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😆",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeBlinkLeft,
        rightEye: .eyeBlinkRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: .jawOpen),
    Emoji(
        image: "😅",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeSquintLeft,
        rightEye: .eyeSquintRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: .jawOpen),
    Emoji(
        image: "😂",
        leftBrow: .browDownLeft,
        rightBrow: .browDownRight,
        leftEye: .eyeBlinkLeft,
        rightEye: .eyeBlinkRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: .jawOpen),
    Emoji(
        image: "🤣",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeBlinkLeft,
        rightEye: .eyeBlinkRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: .jawOpen),
    Emoji(
        image: "🥲",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: nil,
        rightEye: nil,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "☺️",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeBlinkLeft,
        rightEye: .eyeBlinkRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😊",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeSquintLeft,
        rightEye: .eyeSquintRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😇",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeSquintLeft,
        rightEye: .eyeSquintRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "🙂",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: nil,
        rightEye: nil,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "🙃",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: nil,
        rightEye: nil,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😉",
        leftBrow: nil,
        rightBrow: .browDownRight,
        leftEye: nil,
        rightEye: .eyeBlinkRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😉",
        leftBrow: .browDownLeft,
        rightBrow: nil,
        leftEye: .eyeBlinkLeft,
        rightEye: nil,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😌",
        leftBrow: .browDownLeft,
        rightBrow: .browDownRight,
        leftEye: .eyeBlinkLeft,
        rightEye: .eyeBlinkRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😍",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeWideLeft,
        rightEye: .eyeWideRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: .jawOpen),
    Emoji(
        image: "🥰",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeBlinkLeft,
        rightEye: .eyeBlinkRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😘",
        leftBrow: nil,
        rightBrow: .browDownRight,
        leftEye: nil,
        rightEye: .eyeBlinkRight,
        leftMouth: .mouthPucker,
        rightMouth: .mouthPucker,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😗",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: nil,
        rightEye: nil,
        leftMouth: .mouthPucker,
        rightMouth: .mouthPucker,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😙",
        leftBrow: .eyeSquintLeft,
        rightBrow: .eyeSquintRight,
        leftEye: nil,
        rightEye: nil,
        leftMouth: .mouthPucker,
        rightMouth: .mouthPucker,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😚",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeBlinkLeft,
        rightEye: .eyeBlinkRight,
        leftMouth: .mouthPucker,
        rightMouth: .mouthPucker,
        tongue: nil,
        jaw: nil),
    Emoji(
        image: "😋",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeBlinkLeft,
        rightEye: .eyeBlinkRight,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: .tongueOut,
        jaw: nil),
    Emoji(
        image: "😛",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: nil,
        rightEye: nil,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: .tongueOut,
        jaw: .jawOpen),
    Emoji(
        image: "😝",
        leftBrow: nil,
        rightBrow: nil,
        leftEye: .eyeBlinkLeft,
        rightEye: .eyeBlinkLeft,
        leftMouth: .mouthSmileLeft,
        rightMouth: .mouthSmileRight,
        tongue: .tongueOut,
        jaw: .jawOpen),
//    Emoji(
//        image: "😜",
//        leftBrow: nil,
//        rightBrow: nil,
//        leftEye: .regular,
//        rightEye: .regular,
//        leftMouth: .mouthSmile,
//        rightMouth: .mouthSmile,
//        tongue: false),
//    Emoji(
//        image: "🤪",
//        leftBrow: nil,
//        rightBrow: nil,
//        leftEye: .regular,
//        rightEye: .regular,
//        leftMouth: .mouthSmile,
//        rightMouth: .mouthSmile,
//        tongue: false),
//    Emoji(
//        image: "🤨",
//        leftBrow: nil,
//        rightBrow: nil,
//        leftEye: .regular,
//        rightEye: .regular,
//        leftMouth: .mouthSmile,
//        rightMouth: .mouthSmile,
//        tongue: false),
//    Emoji(
//        image: "🧐",
//        leftBrow: nil,
//        rightBrow: nil,
//        leftEye: nil,
//        rightEye: nil,
//        leftMouth: .mouthSmileLeft,
//        rightMouth: .mouthSmileRight,
//        tongue: nil,
//        jaw: .jawOpen),
]
}
// 🤓 😎 🥸 🤩 🥳 😏 😒 😞 😔 😟 😕 🙁 ☹️ 😣 😖 😫 😩 🥺 😢 😭 😤 😠 😡 🤬 🤯 😳 🥵 🥶 😱 😨 😰 😥 😓 🤔 🤭 🤫 😶 😐 😑 😬 🙄 😯 😦 😧 😮 😲 🥱 🤤 😪 😵 🤐 🥴 🤢 🤮 🤒 🤕 🤑 🤠 😈 👿 👹 👺 🤡 💩 👻 👽 🤖 😺 😸 😹 😻 😼 😽 🙀 😿 😾 👀 👅 🙍 🙎 🦹 🐵 🙈 🙊 🌝 🌚 🗿

